/**
 * Field mappings for converting between database and API field formats
 */

import { ModelFieldMappings } from './types';

export const FIELD_MAPPINGS: ModelFieldMappings = {
  user: {
    toApi: {
      id: 'id',
      nickname: 'nickname',
      name: 'name',
      firstName: 'first_name',
      middleName: 'middle_name',
      lastName: 'last_name',
      avatar: 'avatar',
      mobile: 'mobile',
      email: 'email',
      about: 'about',
      isActive: 'is_active',
      isArchived: 'is_archived',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      lastLoginAt: 'last_login_at',
      emailVerified: 'email_verified',
      onboardingCompleted: 'onboarding_completed'
    },
    toDb: {
      id: 'id',
      nickname: 'nickname',
      name: 'name',
      first_name: 'firstName',
      middle_name: 'middleName',
      last_name: 'lastName',
      avatar: 'avatar',
      mobile: 'mobile',
      email: 'email',
      about: 'about',
      is_active: 'isActive',
      is_archived: 'isArchived',
      created_at: 'createdAt',
      updated_at: 'updatedAt',
      last_login_at: 'lastLoginAt',
      email_verified: 'emailVerified',
      onboarding_completed: 'onboardingCompleted'
    }
  },

  project: {
    toApi: {
      id: 'id',
      name: 'name',
      description: 'description',
      code: 'code',
      userId: 'user_id',
      type: 'type',
      isTrial: 'is_trial',
      trialExpiresAt: 'trial_expires_at',
      accountType: 'account_type',
      smsCredits: 'sms_credits',
      whatsappCredits: 'whatsapp_credits',
      voiceCredits: 'voice_credits',
      timezone: 'timezone',
      currency: 'currency',
      defaultSenderId: 'default_sender_id',
      webhookUrl: 'webhook_url',
      webhookSecret: 'webhook_secret',
      isActive: 'is_active',
      isArchived: 'is_archived',
      isSuspended: 'is_suspended',
      suspensionReason: 'suspension_reason',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      name: 'name',
      description: 'description',
      code: 'code',
      user_id: 'userId',
      type: 'type',
      is_trial: 'isTrial',
      trial_expires_at: 'trialExpiresAt',
      account_type: 'accountType',
      sms_credits: 'smsCredits',
      whatsapp_credits: 'whatsappCredits',
      voice_credits: 'voiceCredits',
      timezone: 'timezone',
      currency: 'currency',
      default_sender_id: 'defaultSenderId',
      webhook_url: 'webhookUrl',
      webhook_secret: 'webhookSecret',
      is_active: 'isActive',
      is_archived: 'isArchived',
      is_suspended: 'isSuspended',
      suspension_reason: 'suspensionReason',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  campaign: {
    toApi: {
      id: 'id',
      projectId: 'project_id',
      name: 'name',
      description: 'description',
      type: 'channel', // Map type -> channel for API consistency
      goal: 'goal',
      audience: 'audience',
      contactListIds: 'contact_list_ids',
      filters: 'filters',
      maxBudget: 'max_budget',
      maxMessages: 'max_messages',
      dailyLimit: 'daily_limit',
      scheduledAt: 'scheduled_at',
      timezone: 'timezone',
      status: 'status',
      totalSent: 'total_sent',
      totalDelivered: 'total_delivered',
      totalFailed: 'total_failed',
      totalCost: 'total_cost',
      isActive: 'is_active',
      isArchived: 'is_archived',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      project_id: 'projectId',
      name: 'name',
      description: 'description',
      channel: 'type', // Map channel -> type for database
      goal: 'goal',
      audience: 'audience',
      contact_list_ids: 'contactListIds',
      filters: 'filters',
      max_budget: 'maxBudget',
      max_messages: 'maxMessages',
      daily_limit: 'dailyLimit',
      scheduled_at: 'scheduledAt',
      timezone: 'timezone',
      status: 'status',
      total_sent: 'totalSent',
      total_delivered: 'totalDelivered',
      total_failed: 'totalFailed',
      total_cost: 'totalCost',
      is_active: 'isActive',
      is_archived: 'isArchived',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  template: {
    toApi: {
      id: 'id',
      projectId: 'project_id',
      name: 'name',
      description: 'description',
      messageType: 'channel', // Map messageType -> channel for API consistency
      subject: 'subject',
      content: 'content',
      variables: 'variables',
      category: 'type', // Map category -> type for API consistency
      language: 'language',
      isValidated: 'is_validated',
      validationErrors: 'validation_errors',
      usageCount: 'usage_count',
      lastUsedAt: 'last_used_at',
      isActive: 'is_active',
      isArchived: 'is_archived',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      project_id: 'projectId',
      name: 'name',
      description: 'description',
      channel: 'messageType', // Map channel -> messageType for database
      subject: 'subject',
      content: 'content',
      variables: 'variables',
      type: 'category', // Map type -> category for database
      language: 'language',
      is_validated: 'isValidated',
      validation_errors: 'validationErrors',
      usage_count: 'usageCount',
      last_used_at: 'lastUsedAt',
      is_active: 'isActive',
      is_archived: 'isArchived',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  contact: {
    toApi: {
      id: 'id',
      projectId: 'project_id',
      userId: 'user_id',
      contactListId: 'contact_list_id',
      firstName: 'first_name',
      middleName: 'middle_name',
      lastName: 'last_name',
      fullName: 'full_name',
      mobile: 'mobile',
      email: 'email',
      jobTitle: 'job_title',
      company: 'company',
      department: 'department',
      city: 'city',
      state: 'state',
      country: 'country',
      address: 'address',
      postalCode: 'postal_code',
      preferredLanguage: 'preferred_language',
      timezone: 'timezone',
      isOptedOut: 'is_opted_out',
      optedOutAt: 'opted_out_at',
      optOutReason: 'opt_out_reason',
      optOutMethod: 'opt_out_method',
      isStarred: 'is_starred',
      isSpam: 'is_spam',
      isHidden: 'is_hidden',
      isExcluded: 'is_excluded',
      mobileVerified: 'mobile_verified',
      emailVerified: 'email_verified',
      customFields: 'custom_fields',
      tags: 'tags',
      notes: 'notes',
      source: 'source',
      isActive: 'is_active',
      isArchived: 'is_archived',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      project_id: 'projectId',
      user_id: 'userId',
      contact_list_id: 'contactListId',
      first_name: 'firstName',
      middle_name: 'middleName',
      last_name: 'lastName',
      full_name: 'fullName',
      mobile: 'mobile',
      email: 'email',
      job_title: 'jobTitle',
      company: 'company',
      department: 'department',
      city: 'city',
      state: 'state',
      country: 'country',
      address: 'address',
      postal_code: 'postalCode',
      preferred_language: 'preferredLanguage',
      timezone: 'timezone',
      is_opted_out: 'isOptedOut',
      opted_out_at: 'optedOutAt',
      opt_out_reason: 'optOutReason',
      opt_out_method: 'optOutMethod',
      is_starred: 'isStarred',
      is_spam: 'isSpam',
      is_hidden: 'isHidden',
      is_excluded: 'isExcluded',
      mobile_verified: 'mobileVerified',
      email_verified: 'emailVerified',
      custom_fields: 'customFields',
      tags: 'tags',
      notes: 'notes',
      source: 'source',
      is_active: 'isActive',
      is_archived: 'isArchived',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  smsMessage: {
    toApi: {
      id: 'id',
      messageId: 'message_id',
      projectId: 'project_id',
      campaignId: 'campaign_id',
      templateId: 'template_id',
      from: 'from',
      to: 'to',
      message: 'message',
      messageType: 'message_type',
      messageParts: 'message_parts',
      channel: 'channel',
      provider: 'provider',
      telco: 'telco',
      networkCode: 'network_code',
      status: 'status',
      statusCode: 'status_code',
      deliveryStatus: 'delivery_status',
      deliveryDescription: 'delivery_description',
      direction: 'direction',
      providerMessageId: 'provider_message_id',
      providerResponse: 'provider_response',
      providerTimestamp: 'provider_timestamp',
      deliveredAt: 'delivered_at',
      failureReason: 'failure_reason',
      retryCount: 'retry_count',
      cost: 'cost',
      price: 'price',
      priceUnit: 'price_unit',
      scheduledAt: 'scheduled_at',
      sentAt: 'sent_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      message_id: 'messageId',
      project_id: 'projectId',
      campaign_id: 'campaignId',
      template_id: 'templateId',
      from: 'from',
      to: 'to',
      message: 'message',
      message_type: 'messageType',
      message_parts: 'messageParts',
      channel: 'channel',
      provider: 'provider',
      telco: 'telco',
      network_code: 'networkCode',
      status: 'status',
      status_code: 'statusCode',
      delivery_status: 'deliveryStatus',
      delivery_description: 'deliveryDescription',
      direction: 'direction',
      provider_message_id: 'providerMessageId',
      provider_response: 'providerResponse',
      provider_timestamp: 'providerTimestamp',
      delivered_at: 'deliveredAt',
      failure_reason: 'failureReason',
      retry_count: 'retryCount',
      cost: 'cost',
      price: 'price',
      price_unit: 'priceUnit',
      scheduled_at: 'scheduledAt',
      sent_at: 'sentAt',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  whatsappMessage: {
    toApi: {
      id: 'id',
      messageId: 'message_id',
      projectId: 'project_id',
      whatsappAccountId: 'whatsapp_account_id',
      phoneNumberId: 'phone_number_id',
      templateId: 'template_id',
      from: 'from',
      to: 'to',
      direction: 'direction',
      messageType: 'message_type',
      content: 'content',
      templateName: 'template_name',
      templateLanguage: 'template_language',
      templateParameters: 'template_parameters',
      status: 'status',
      statusCode: 'status_code',
      statusDescription: 'status_description',
      providerMessageId: 'provider_message_id',
      providerResponse: 'provider_response',
      providerTimestamp: 'provider_timestamp',
      cost: 'cost',
      whatsappFee: 'whatsapp_fee',
      platformFee: 'platform_fee',
      totalCost: 'total_cost',
      currency: 'currency',
      conversationId: 'conversation_id',
      sentAt: 'sent_at',
      deliveredAt: 'delivered_at',
      readAt: 'read_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      message_id: 'messageId',
      project_id: 'projectId',
      whatsapp_account_id: 'whatsappAccountId',
      phone_number_id: 'phoneNumberId',
      template_id: 'templateId',
      from: 'from',
      to: 'to',
      direction: 'direction',
      message_type: 'messageType',
      content: 'content',
      template_name: 'templateName',
      template_language: 'templateLanguage',
      template_parameters: 'templateParameters',
      status: 'status',
      status_code: 'statusCode',
      status_description: 'statusDescription',
      provider_message_id: 'providerMessageId',
      provider_response: 'providerResponse',
      provider_timestamp: 'providerTimestamp',
      cost: 'cost',
      whatsapp_fee: 'whatsappFee',
      platform_fee: 'platformFee',
      total_cost: 'totalCost',
      currency: 'currency',
      conversation_id: 'conversationId',
      sent_at: 'sentAt',
      delivered_at: 'deliveredAt',
      read_at: 'readAt',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  paymentMethod: {
    toApi: {
      id: 'id',
      name: 'name',
      type: 'type',
      provider: 'provider',
      isActive: 'is_active',
      configuration: 'configuration',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      name: 'name',
      type: 'type',
      provider: 'provider',
      is_active: 'isActive',
      configuration: 'configuration',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  role: {
    toApi: {
      id: 'id',
      name: 'name',
      description: 'description',
      isActive: 'is_active',
      isArchived: 'is_archived',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      name: 'name',
      description: 'description',
      is_active: 'isActive',
      is_archived: 'isArchived',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  },

  permission: {
    toApi: {
      id: 'id',
      name: 'name',
      description: 'description',
      resource: 'resource',
      action: 'action',
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    toDb: {
      id: 'id',
      name: 'name',
      description: 'description',
      resource: 'resource',
      action: 'action',
      created_at: 'createdAt',
      updated_at: 'updatedAt'
    }
  }
};